### PR TITLE
Add minimal tests

### PR DESCRIPTION
**Pull request by ziima**
I've tried to add minimal tests. I've read #22 and I tried to add as minimal code as possible.

Let me know if you request further changes.

### CODE REVIEW

**Comment by ziima** [comment]
I'd like to make more changes, but I just don't feel comfortable with no tests around.

**Comment by fdemmer** [comment]
Thank you for your contribution(s)!

Is this finished? How do you run the test?

**Comment by ziima** [comment]
This part is. Currently, the tests may be run by
```sh
DJANGO_SETTINGS_MODULE=django_weasyprint.tests.settings  python -m django test django_weasyprint
```
but I'd recommend to add `tox` later on. I'd leave that for another issue.

**Comment by fdemmer** [comment]
included with further work in 69be0583ab2244d221e7fbf32e654fb47ecb4821

**Pull request closed without merging**
